### ISSUE TITLE
Training dataset?

### ISSUE THREAD

**Issue by tianyikillua** [igrega348/energy-equiv-lattice-gnn#1]
Hi,

I was trying to reproduce the results reported in your paper. Maybe it is a stupid question...could you please mention how to extract the `0imp` dataset to train your model, from the `cat_0x.lat` files [downloaded here](https://www.repository.cam.ac.uk/items/e2a84a1b-4a44-49b9-92f7-c30d3ad22e90)?

Thanks!

**Comment by igrega348** [comment]
Hi @tianyikillua,

Thanks for reaching out. I added jupyter notebook `assemble_datasets.ipynb` and `train/val_base_names.txt` to `scripts` which can be used to put together datasets from `cat_xx.lat` files.
Please let me know if this gets the job done.

--Ivan

**Comment by tianyikillua** [comment]
Thanks!! Will have a try and come back here :-)

**Comment by tianyikillua** [comment]
Thanks for your efforts. It's training well :-)

As a side note, I had to rename `node_attrs` to `x` in [GLAMM_Dataset](https://github.com/igrega348/energy-equiv-lattice-gnn/blob/main/gnn/datasets.py#L260C17-L260C27) and make necessary changes in the associated classes. There seems to be a name collision with `pytorch_gemetric.data.Data.node_attrs()`.
